version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest-testing-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: billal
      POSTGRES_PASSWORD: hossain
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U billal -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: nest-testing-redis
    ports:
      - "6379:6379"
    networks:
      - nest-network
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  nest-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
